name: Create or Update OpenTelemetry Update PR

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-or-update-deps-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for pushing changes
    steps:
      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version: 22

      - run: npm install -g npm@latest

      - run: npm ci

      - name: Create/Update Release PR
        run: |
          git config user.name otelbot
          git config user.email 197425009+otelbot@users.noreply.github.com
          git checkout -b otelbot/feat-update-otel-deps
          node ./scripts/update-otel-deps.js
          git commit -am "feat(deps): update deps matching '@opentelemetry/*'"
          git push --set-upstream origin otelbot/feat-update-otel-deps --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create PR
        run: |
          gh pr create --title "feat(deps): update deps matching '@opentelemetry/*'" --body 'Updates all `@opentelemetry/*` dependencies to latest'
        env:
          GITHUB_TOKEN: ${{ steps.otelbot-token.outputs.token }}
